### ISSUE TITLE
Error: Cannot find module 'fs/promises' when 'npm run serve'.

### ISSUE THREAD

**Issue by AndreyNag** [siacentral/host-manager#66]
Hi. I try to start host-manager server to access my sia-host via internet but get error:
`sia@sia-host:~/host-manager$ npm run serve

> Sia-Host-Manager@1.1.1 serve
> vue-cli-service electron:serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 2162ms                                                                       18:27:59

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.240:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

⠋  Bundling main process...

 DONE  Compiled successfully in 904ms                                                                        18:28:00

  File             Size                                            Gzipped

  dist/index.js    3130.01 KiB                                     646.87 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
App threw an error during load
Error: Cannot find module 'fs/promises'
Require stack:
- /home/sia/host-manager/dist/index.js
- /home/sia/host-manager/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack:///external_%22fs/promises%22?:1:18)
    at Object.fs/promises (/home/sia/host-manager/dist/index.js:5726:1)
    at __webpack_require__ (/home/sia/host-manager/dist/index.js:20:30)
    at eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:8:20)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'fs/promises'
Require stack:
- /home/sia/host-manager/dist/index.js
- /home/sia/host-manager/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack:///external_%22fs/promises%22?:1:18)
    at Object.fs/promises (/home/sia/host-manager/dist/index.js:5726:1)
    at __webpack_require__ (/home/sia/host-manager/dist/index.js:20:30)
    at eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:8:20)
sia@sia-host:~/host-manager$
`
Ubuntu 20.04.3 LTS Server
Node.js v17.1.0
npm v8.1.2
Thanx for attention.

**Comment by AndreyNag** [comment]
I didn't wait for a response from the developers and installed a GUI on the server. Launched https://github.com/siacentral/host-manager/releases/download/v1.1.1/Sia-Host-Manager-v1.1.1.AppImage and I got the same error.
